In [1]:
#Create a row vector and a column vector
import numpy as np
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1],
                         [2],
                         [3],
                         [4]])
print(vector_row.shape)
print(vector_column.shape)

(1, 5)
(4, 1)


In [5]:
#Transpose the row vector into a column vector 
#Calculate the L1, l2, linf norm

from numpy.linalg import norm
new_vector = vector_row.T
print(new_vector)
norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)
print('L_1 is: %.1f'%norm_1)
print('L_2 is: %.1f'%norm_2)
print('L_inf is: %.1f'%norm_inf)

[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L_1 is: 15.0
L_2 is: 7.4
L_inf is: 5.0


In [8]:
# Compute the angle between 2 vectors
from numpy import arccos, dot

v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
theta = \
    arccos(dot(v,w.T)/(norm(v)*norm(w)))
print(theta)

[[0.97992471]]


In [9]:
# the geometric interpretation of the cross product is a vector perpendicular to both v and w 
# with length equal to the area enclosed by the parallelogram created by the two vectors
# compute cross product
v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])
print(np.cross(v,w))

[[ 0  0 -6]]


In [10]:
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])
x = 3*v-2*w+4*u
print(x)

[[-8 -1  4]]


In [12]:
#Product of 2 matrices is achieved using the dot method in Numpy. 
#The error when calculating product of Q and P is expected.
P = np.array([[1,7],[2,3],[5,0]])
Q = np.array([[2,6,3,1], [1,2,3,4]])
print(P)
print(Q)
print(np.dot(P, Q))
np.dot(Q, P)

[[1 7]
 [2 3]
 [5 0]]
[[2 6 3 1]
 [1 2 3 4]]
[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [13]:
# A square matrix is an n x n matrix (same number of rows as columns). The determinant is an important property 
# of square matrices. 
# The identity matrix is a square matrix with ones on the diagonal and zeroes elsewhere.
from numpy.linalg import det

M = np.array([[0,2,1,3], 
             [3,2,8,1], 
             [1,0,0,3],
             [0,3,2,1]])
print('M:\n', M)

print('Determinant: %.1f'%det(M))
I = np.eye(4)
print('I:\n', I)
print('M*I:\n', np.dot(M, I))

M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0
I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


In [14]:
# The inverse of a square matrix is a matrix of the same size
#there are matrices that do not have inverses. These matrices are called singular. 
#Matrices that do have an inverse are called nonsingular.
#One way to determine if a matrix is singular is by computing its determinant. 
#If the determinant is 0, then the matrix is singular; if not, the matrix is nonsingular.

from numpy.linalg import inv

print('Inv M:\n', inv(M))
P = np.array([[0,1,0],
              [0,0,0],
              [1,0,1]])
print('det(p):\n', det(P))

Inv M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]
det(p):
 0.0


In [15]:
#The condition number is a measure of how ill-conditioned a matrix is, 
#and it can be computed using Numpy’s function cond from linalg. 
#The higher the condition number, the closer the matrix is to being singular.

from numpy.linalg import cond, matrix_rank

A = np.array([[1,1,0],
             [0,1,0],
             [1,0,1]])

print('Condition number:\n', cond(A))
print('Rank:\n',matrix_rank(A))
y = np.array([[1], [2], [1]])
A_y = np.concatenate((A, y), axis = 1)
print('Augmented matrix:\n', A_y)

Condition number:
 4.048917339522305
Rank:
 3
Augmented matrix:
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]


In [17]:
u = np.array([[4, 3, -5],
             [0, -2.5, 2.5],
             [0, 0, 12]])
l = np.array([[1,0,0],
             [-0.5, 1, 0],
             [2, -0.8, 1]])

print('LU=',np.dot(l,u))

LU= [[ 4.  3. -5.]
 [-2. -4.  5.]
 [ 8.  8.  0.]]


In [18]:
#check if the coefficient matrix is diagonally dominant or not.

a = [[8, 3, -3], [-2, -8, 5], [3, 5, 10]]

# Find diagonal coefficients
diag = np.diag(np.abs(a)) 

# Find row sum without diagonal
off_diag = np.sum(np.abs(a), axis=1) - diag 

if np.all(diag > off_diag):
    print('matrix is diagonally dominant')
else:
    print('NOT diagonally dominant')

matrix is diagonally dominant


In [20]:
# Since it is guaranteed to converge, we can use Gauss-Seidel method to solve it.
# sample is 8x1 + 3x2 - 3x3 = 14
#          -2x1 - 8x2 + 5x3 = 5
#           3x1 + 5x2 + 10x3 = -8
# [[8, 3, -3], [-2, -8, 5], [3, 5, 10]]

x1 = 0
x2 = 0
x3 = 0
epsilon = 0.01
converged = False

x_old = np.array([x1, x2, x3])

print('Iteration results')
print(' k,    x1,    x2,    x3 ')
for k in range(1, 50):
    x1 = (14-3*x2+3*x3)/8
    x2 = (5+2*x1-5*x3)/(-8)
    x3 = (-8-3*x1-5*x2)/(10) #example had -5 here where I put 10 but not sure why the example had -5
    x = np.array([x1, x2, x3])
    # check if it is smaller than threshold
    dx = np.sqrt(np.dot(x-x_old, x-x_old))
    
    print("%d, %.4f, %.4f, %.4f"%(k, x1, x2, x3))
    if dx < epsilon:
        converged = True
        print('Converged!')
        break
        
    # assign the latest x value to the old value
    x_old = x

if not converged:
    print('Not converge, increase the # of iterations')

Iteration results
 k,    x1,    x2,    x3 
1, 1.7500, -1.0625, -0.7937
2, 1.8508, -1.5838, -0.5633
3, 2.1327, -1.5103, -0.6847
4, 2.0596, -1.5678, -0.6340
5, 2.1002, -1.5463, -0.6569
6, 2.0835, -1.5565, -0.6468
7, 2.0911, -1.5520, -0.6513
Converged!


In [25]:
#using solve function in numpy to solve systems of equations
A = np.array([[4, 3, -5],
             [-2, -4, 5],
             [8, 8, 0]])
y = np.array([2, 5, -3])

x = np.linalg.solve(A, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


In [26]:
# solve using the matrix inversion approach
A_inv = np.linalg.inv(A)

x = np.dot(A_inv, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


In [27]:
# Get the L and U for the above matrix
from scipy.linalg import lu

P, L, U = lu(A)
print('P:\n', P)
print('L:\n', L)
print('U:\n', U)
print('LU:\n',np.dot(L, U))

P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
 [[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [ 0.5   0.5   1.  ]]
U:
 [[ 8.   8.   0. ]
 [ 0.  -2.   5. ]
 [ 0.   0.  -7.5]]
LU:
 [[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]


In [28]:
print(np.dot(P, A))

[[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]
